In [1]:
!pip install protobuf

In [2]:
from transformers import LlamaForCausalLM, CodeLlamaTokenizer

/home/jnainani_umass_edu/.conda/envs/finetuning/lib/python3.10/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/jnainani_umass_edu/.conda/envs/finetuning/lib/python3.10/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/jnainani_umass_edu/.conda/envs/finetuning/lib/python3.10/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(


In [3]:
tokenizer = CodeLlamaTokenizer.from_pretrained("codellama/CodeLlama-7b-hf")
model = LlamaForCausalLM.from_pretrained("codellama/CodeLlama-7b-hf")
PROMPT = '''def remove_non_ascii(s: str) -> str:
    """ <FILL_ME>
    return result
'''

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
tokenizer = CodeLlamaTokenizer.from_pretrained("codellama/CodeLlama-7b-Instruct-hf")
model = LlamaForCausalLM.from_pretrained("codellama/CodeLlama-7b-Instruct-hf")

# tokenizer = AutoTokenizer.from_pretrained("codellama/CodeLlama-7b-Instruct-hf")
# model = AutoModelForCausalLM.from_pretrained("codellama/CodeLlama-7b-Instruct-hf")

PROMPT = '''def remove_non_ascii(s: str) -> str:
    """ <FILL_ME>
    return result
'''

/home/jnainani_umass_edu/.conda/envs/finetuning/lib/python3.10/site-packages/huggingface_hub/file_download.py:979: UserWarning: Not enough free disk space to download the file. The expected file size is: 9976.70 MB. The target location /home/jnainani_umass_edu/.cache/huggingface/hub only has 5242.88 MB free disk space.
  warnings.warn(
/home/jnainani_umass_edu/.conda/envs/finetuning/lib/python3.10/site-packages/huggingface_hub/file_download.py:979: UserWarning: Not enough free disk space to download the file. The expected file size is: 9976.70 MB. The target location /home/jnainani_umass_edu/.cache/huggingface/hub/models--codellama--CodeLlama-7b-Instruct-hf/blobs only has 5242.88 MB free disk space.
  warnings.warn(


In [4]:
input_ids = tokenizer(PROMPT, return_tensors="pt")["input_ids"]
generated_ids = model.generate(input_ids, max_new_tokens=128)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


In [5]:
PROMPT2 = '''def remove_non_ascii(s: str) -> str:
    """
    return result
'''

In [8]:
input_ids = tokenizer(PROMPT, return_tensors="pt")["input_ids"]
print(input_ids)

print(tokenizer(PROMPT2, return_tensors="pt")["input_ids"])

tensor([[    1, 32007,   822,  3349, 29918,  5464, 29918,   294, 18869, 29898,
         29879, 29901,   851, 29897,  1599,   851, 29901,    13,  1678,  9995,
         29871, 32008,    13,  1678,   736,  1121,    13, 32009]])
tensor([[    1,   822,  3349, 29918,  5464, 29918,   294, 18869, 29898, 29879,
         29901,   851, 29897,  1599,   851, 29901,    13,  1678,  9995,    13,
          1678,   736,  1121,    13]])


In [9]:
tokenizer.batch_decode([32007,29871, 32008, 32009])

['<PRE>', '', '<SUF>', '<MID>']

In [10]:
filling = tokenizer.batch_decode(generated_ids[:, input_ids.shape[1]:], skip_special_tokens = True)[0]
print(PROMPT.replace("<FILL_ME>", filling))

def remove_non_ascii(s: str) -> str:
    """ Remove non-ASCII characters from a string.

    Args:
        s: The string to remove non-ASCII characters from.

    Returns:
        The string with non-ASCII characters removed.
    """
    result = ""
    for c in s:
        if ord(c) < 128:
            result += c
    return result



In [11]:
PROMPT = '''#include <iostream>

void modifyValue(int<FILL_ME>value) {
    value += 10;
}

int main() {
    int num = 5;
    modifyValue(num);
    std::cout << "Modified value: " << num << std::endl;
    return 0;
}
'''

input_ids = tokenizer(PROMPT, return_tensors="pt")["input_ids"]
generated_ids = model.generate(input_ids, max_new_tokens=1)
filling = tokenizer.batch_decode(generated_ids[:, input_ids.shape[1]:], skip_special_tokens = True)[0]
print(filling)
# print(PROMPT.replace("<FILL_ME>", filling))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


&


In [20]:
PROMPT = '''def palindrome(s: <FILL_ME> ):
return s[::-1] == s
'''

input_ids = tokenizer(PROMPT, return_tensors="pt")["input_ids"]
generated_ids = model.generate(input_ids, max_new_tokens=2)
filling = tokenizer.batch_decode(generated_ids[:, input_ids.shape[1]:], skip_special_tokens = True)[0]
print(filling)
# print(PROMPT.replace("<FILL_ME>", filling))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


str):


In [15]:
generated_ids[:, input_ids.shape[1]:]

tensor([[   13, 29898, 29874, 29974, 29890]])

In [29]:
PROMPT = '''Custom Entities:
def X(a, b):
    return a + b
def Y(a, b):
    return a - b
def Z(a, b):
    return a * b
def W(a, b):
    return a / b
def G(a, b):
    return a ** b
def H(a, b):
    return a % b
def F(a, b):
    return a < b
def K(a, b):
    return a > b
def O(a, b):
    return a <= b
def P(a, b):
    return a >= b
def D(a, b):
    return a == b

the name of custom entity that uses "<=" operator is 
'''

input_ids = tokenizer(PROMPT, return_tensors="pt")["input_ids"]
generated_ids = model.generate(input_ids, max_new_tokens=5)
filling = tokenizer.batch_decode(generated_ids[:, input_ids.shape[1]:], skip_special_tokens = True)[0]
print(filling)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.



O(a,
